name: Generate Docs

on:
  push:
    branches:
      - latest

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 10
      - run: npm install
      - run: |
          cd docs
          git init
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git remote add origin git@github.com:${GITHUB_REPOSITORY}.git
          git checkout -b gh-pages
          git add -A
          git commit -m "Docs update: ${GITHUB_SHA}"
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PUSH_TOKEN }}
          branch: gh-pages
          force: true
          directory: docs
